import React from "react";
import ImgHeading from "../components/Partials/ImgHeading";

const TermsConditionPage = () => {
  return (
    <section
      id="termsCondition"
      className="flex h-full w-full flex-col items-center justify-center bg-[#FBFBFB]"
    >
      <ImgHeading text="Terms And" blueText="Conditions" />

      <div className="flex w-full flex-col items-center justify-center pb-16 pt-14 lg:max-w-[80rem]">
        <div className="flex h-full w-full flex-col px-10 md:px-8 lg:flex-row">
          <p className="flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            Welcome to Quick Finz! <br />
            <span>
              These terms and conditions outline the rules and regulations for
              the use of Quick Finz's Website, located at www.quickfinz.com.
            </span>
            <span>
              By accessing this website we assume you accept these terms and
              conditions.Do not continue to use Quick Finz if you do not agree
              to take all of the terms and conditions stated on this page.
            </span>
            <span>
              The following terminology applies to these Terms and Conditions,
              Privacy Statement and Disclaimer Notice and all Agreements:
              "Client", "You" and "Your" refers to you, the person log on this
              website and compliant to the Company's terms and conditions. "The
              Company", "Ourselves", "We", "Our" and "Us", refers to our
              Company. "Party", "Parties", or "Us", refers to both the Client
              and ourselves. All terms refer to the offer, acceptance and
              consideration of payment necessary to undertake the process of our
              assistance to the Client in the most appropriate manner for the
              express purpose of meeting the Client's needs in respect of
              provision of the Company's stated services, in accordance with and
              subject to, prevailing law of in. Any use of the above terminology
              or other words in the singular, plural, capitalization and/or
              he/she or they, are taken as interchangeable and therefore as
              referring to same.
            </span>
            <span>
              The terms and conditions outlined in this Agreement apply to the
              use and access of the "www.quickfinz.com" website and its Mobile
              Application, collectively referred to as the "Website." Quick
              Finz, incorporated under the Companies Act, 1956, is the operator
              and manager of the Website and will be referred to as "Company" or
              "Quick Finz" in this Agreement.
            </span>
            <span>
              This "Agreement" is an electronic record, generated by a computer
              system, and does not require physical or digital signatures. It is
              published in accordance with the provisions of Rule 3 of the
              Information Technology (Intermediaries guidelines) 2011, which
              outlines due diligence requirements for accessing or using this
              Website.
            </span>
            <span>
              Please carefully read and consider these Terms and Conditions.
              Your acceptance of the terms contained herein constitutes an
              agreement between you and the Company for the purposes defined
              hereunder.
            </span>
            <span>
              The Company is providing access to information related to various
              financial products and services, including but not limited to loan
              and credit card facilities, savings accounts, fixed deposits, and
              mutual funds, collectively referred to as "Services". These
              Services may be provided by Quick Finz or third-party providers,
              and may also include ancillary services such as credit check
              services and retrieval of information from third-party sites such
              as bank sites. The Company will make commercially reasonable
              efforts to provide these Services and ancillary services, but your
              decision to participate in these services is entirely voluntary
              and at your own discretion.
            </span>
            <span>
              By using the Services, you authorize and agree that Company may
              share your information with its group companies and third parties,
              for the purposes of joint marketing, offering various services,
              report generation, or providing you with value-added services in
              connection with the Services you have selected or otherwise. You
              also agree to receive communications from the Company, or its
              third-party vendors, business partners, or marketing affiliates,
              via email, telephone, and/or SMS regarding the Services and
              ancillary services updates, information, promotional emails,
              and/or product announcements. You agree to receive these
              communications at the mobile number you have provided, even if it
              is registered under the DND/NCPR list under TRAI regulations. In
              addition, you authorize Company to share/disclose your information
              with third-party service providers, affiliates, group companies,
              or authorized agents for this purpose.
            </span>
            <span>
              Your continued usage of the Services and ancillary services from
              time to time would also constitute acceptance of the Terms and
              Conditions including any updation or modification thereof and you
              would be bound by this Agreement until this Agreement is
              terminated as per provisions defined herein.
            </span>
            <span>
              Company will retain and use your information as necessary to
              comply with our legal obligations, resolve disputes and enforce
              our agreements entered into for providing Services and ancillary
              services.
            </span>
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">
            Your Registration/Account
          </h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            <span>
              In consideration of your use of the Website and registering with
              us, you represent that you are of legal age to form a binding
              contract and are not a person barred from receiving services under
              the laws of India or other applicable jurisdiction and will only
              use the Website to make legitimate purchases for you or for
              another person for whom you are legally authorized to act (and
              will inform such other persons about the Terms and Conditions
              and/or Privacy Policy) that apply to the purchase you have made on
              their behalf (including all rules and restrictions applicable
              thereto).
            </span>

            <span>
              You shall provide true, accurate, current and complete information
              about yourself and undertake to inform/update of any change in
              your Registration Information promptly and keep it up-to-date and
              accurate at all times, as it has a direct bearing on the provision
              of Services and ancillary services by or through Company. You
              agree not to misrepresent your identity nor will you make an
              attempt to make an unlawful access to the Website or use of the
              Services. Additional terms and conditions will apply to your
              purchase of services that you select. Please read these additional
              terms and conditions carefully.
            </span>

            <span>
              You agree and understand that you are solely responsible for
              maintaining the confidentiality of your password which, together
              with your Login ID (as may be applicable in accordance with the
              Service selected), allows you to access the Service. That Login ID
              and password, together with any mobile number or other contact
              information you provide, form your ("Registration Information").
              You agree that you are responsible for maintaining the
              confidentiality of your Login ID and password, and for restricting
              access to your computer. You agree to accept responsibility for
              all activities that occur through your account or password.
              Because of this, we strongly recommend that you exit/ logout from
              your account at the end of each session. You agree to notify
              Company immediately of any unauthorized use of your account or any
              other breach of security. You further agree that Company shall not
              be liable for any unauthorized use or access, unless it is proved
              that the unauthorized use or access occurred solely due to reasons
              directly attributable to Company.
            </span>
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">Eligibility</h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            By availing the services offered by the Company, you confirm that
            you are a resident of India, at least 18 years of age, and possess
            the legal capacity to contract as defined under the Indian Contract
            Act of 1872.
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">Privacy Policy</h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            Upon accessing the Website and utilizing any related services, you
            give your consent to the use of your personal information as
            specified in our Privacy Policy. This document details how the
            Company handles your personal information when you access the
            Website and other related services.
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">
            Customer Due Diligence requirements (CDD)
          </h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            You acknowledge and agree that Our Company may conduct customer due
            diligence (CDD) measures as required for Know Your Customer (KYC)
            purposes when facilitating financial transactions through the
            website. This may include obtaining mandatory information from you,
            as a customer, when requesting a loan, credit card, mutual fund, or
            other financial product from banks or financial institutions, in
            compliance with the Prevention of Money Laundering Act ("PMLA") and
            its rules. Our Company may collect sufficient information to verify
            the identity of each new customer/user and establish the nature of
            the relationship between you and the bank/financial institution to
            its satisfaction or as required by the applicable PMLA Act and
            rules. You also acknowledge that Our Company may implement enhanced
            due diligence measures, including additional documentation, to
            ensure compliance with customer due diligence requirements in
            accordance with the PMLA Act and rules.
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">
            Third Party Links/Offers
          </h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            This Website may provide links to other websites or resources. Since
            the Company has no control over such third party websites and
            resources, you acknowledge and agree that Company is not responsible
            for the availability of such external sites or resources, and does
            not endorse and is not responsible or liable for any content,
            advertising, products or other materials on or available from such
            sites or resources. You further acknowledge and agree that Company
            shall not be responsible or liable, directly or indirectly, for any
            damage or loss caused or alleged to be caused by or in connection
            with use of or reliance on any such content, goods or services
            available on or through any such site or resource. Your interaction
            with any third party accessed through the Website is at your own
            risk, and Company will have no liability with respect to the acts,
            omissions, errors, representations, warranties, breaches or
            negligence of any such third parties or for any personal injuries,
            death, property damage, or other damages or expenses resulting from
            your interactions with the third parties.
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">
            Disclaimer of Warranty
          </h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            <span>
              You explicitly acknowledge and agree that your utilization of the
              Services, ancillary services, and all information, products, and
              other content (including that of third parties) available on or
              accessible from the Website is solely at your own risk. The
              Services and ancillary services are provided "as is" and "as
              available" without any representations, warranties, or guarantees,
              express or implied, regarding the accuracy, reliability, or
              completeness of the content on the Website or the services
              (whether or not sponsored by third-party service providers). The
              Company expressly disclaims any warranties of non-infringement or
              fitness for a particular purpose.
            </span>

            <span>
              You explicitly acknowledge and agree that your utilization of the
              Services, ancillary services, and all information, products, and
              other content (including that of third parties) available on or
              accessible from the Website is solely at your own risk. The
              Services and ancillary services are provided "as is" and "as
              available" without any representations, warranties, or guarantees,
              express or implied, regarding the accuracy, reliability, or
              completeness of the content on the Website or the services
              (whether or not sponsored by third-party service providers). The
              Company expressly disclaims any warranties of non-infringement or
              fitness for a particular purpose.
            </span>

            <span>
              Company and its service providers, affiliates, business partners
              make no warranty that (i) the services will meet your
              requirements, (ii) the services will be uninterrupted, timely,
              secure, or error-free, (iii) the results that may be obtained from
              the use of the services will be accurate or reliable, (iv) the
              quality of any products, services, information, or other material
              purchased or obtained by you through the services will meet your
              expectations, and (v) any errors in the technology will be
              corrected.
            </span>

            <span>
              Prices for Products available on our Website and are incorporated
              into this TERMS AND CONDITIONSs by reference. All prices, whether
              specified or not, are in Indian rupees. Prices, Products and
              Services are offered by the Company’s business partners, and may
              change in accordance with the brand guidelines or other terms and
              conditions applicable to each of the business partners of Quick
              Finz. In some cases Services and prices are offered by the Company
              itself and it reserves the right to modify the use and prices of
              such Services. You further undertake that by initiating a
              transaction, you are entering into a legally binding and
              enforceable contract with these business partners of the Company,
              to purchase the products or avail the services using such payment
              facilities as may be permitted by applicable laws and as may be
              accepted by the Company.
            </span>

            <span>
              The Company does not charge any registration/membership or
              browsing fee. However, the Company reserves the absolute right to
              charge any fee for registration/ membership or browsing fee at any
              time.. All such fees that the Company may charge will be intimated
              to the users and such change shall automatically become effective
              immediately after they are posted on the Website. All such fees
              charged by the Company shall be in Indian Rupees. Your continued
              use of the Company shall be deemed as an acceptance of the amended
              terms of the TERMS AND CONDITIONS.
            </span>

            <span>
              The Company may enter into agreements with third party payment
              gateway aggregators and financial institutions authorized by the
              Reserve Bank of India for collection, refund and remittance and to
              facilitate payment between you, Quick Finz and its business
              partners, as the case may be. The Company shall initiate the
              remittance of the payments made by you and the date of completion
              of transaction shall be after the products are delivered to you or
              after the Services are rendered to you and such other additional
              time as may be agreed between Website and its business partners,
              as the case may be.
            </span>

            <span>
              While availing any of the payment method/s available on the
              Website, the Company will not be responsible or assume any
              liability, whatsoever in respect of any loss or damage arising
              directly or indirectly to you due to:
            </span>
          </p>

          <ul className="my-4 ml-7 mt-2 flex list-image-[url('/src/assets/hand.svg')] flex-col gap-3 text-base font-medium leading-[1.8rem]">
            <li>Lack of authorization for any transaction/s, or</li>
            <li>Any payment issues arising out of the transaction, or</li>
            <li>
              Illegitimacy of the payment methods (credit/debit card frauds
              etc.) being used by a you;
            </li>
            <li>Decline of transaction for any other reason(s)</li>
          </ul>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            <span>
              Notwithstanding anything contained herein, the Website reserves
              the right to conduct additional verification for security or other
              reasons if it is not satisfied with the creditability of you/your
              transaction.
            </span>

            <span>
              Use of the payment facilities provided by the Website shall not
              render the Website liable or responsible for the non-delivery,
              non-receipt, non-payment, damage, breach of representations and
              warranties, non-provision of after sales or warranty services or
              fraud as regards the products or services listed on the Website.
              The Website shall not be responsible for any damages, interests or
              claims arising from not processing a transaction.
            </span>

            <span>
              You hereby agree to provide accurate information, such as
              credit/debit information for purchasing any Service or product on
              or through the Website. You further warrant that you shall not use
              payment information or instrument that is not lawfully owned by
              you. In addition to this TERMS AND CONDITIONSs, the terms and
              conditions of the bank or other financial institution shall also
              be applicable to every user. The Website disclaims any liability
              arising out of declining of payment by such bank or financial
              institution.
            </span>

            <span>
              Quick Finz may in its sole discretion impose limits on the number
              of transaction which an individual holding a financial instrument
              may use for payment for products or services. Additionally, the
              Website reserves the right to refuse to process transactions
              exceeding such limit and transactions by you that have incurred
              questionable charges and amounts.
            </span>

            <span>
              Quick Finz is merely a facilitator for providing you with payment
              channels through automated online electronic payments (either
              itself or through its payment gateway service providers), cash on
              delivery, collection and remittance facility for the payment of
              products purchased by the User on the Website using the existing
              authorized banking infrastructure and credit card payment gateway
              networks (of either the Website or Service Providers).
            </span>

            <span>
              Quick Finz shall not be held responsible and shall bear no
              liability in case of failure or delay of delivering the products
              or services including any damage or loss caused to you due to such
              delay. No deliveries of the products/services shall be made
              outside the territorial boundaries of India.
            </span>
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">
            Group Insurance Policy
          </h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            You understand that as a part of the Services provided by the
            Company, it may further offer you group insurance coverage’s from
            different insurers for which Quick Finz Marketing And Consulting
            Private Limited shall be the Master Policy Holder ("MPH") provided
            you are a customer of the Company. Such insurance coverage shall be
            governed by and subject to the terms, conditions, and exclusions,
            limitations thereof as per the guidelines issued by the Insurance
            Regulatory And Development Authority of India ("IRDAI").
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">
            Limitation of Liability
          </h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            <span>
              You expressly understand and agree that the Company (including its
              subsidiaries, affiliates, directors, officers, employees,
              representatives and providers) shall not be liable for any direct,
              indirect, incidental, special, consequential or exemplary damages,
              including but not limited to damages for loss of profits,
              opportunity, goodwill, use, data or other intangible losses, even
              if Company has been advised of the possibility of such damages,
              resulting from (i) any failure or delay (including without
              limitation the use of or inability to use any component of the
              Website), or (ii) any use of the Website or content, or (iii) the
              performance or non-performance by us or any provider, even if we
              have been advised of the possibility of damages to such parties or
              any other party, or (b) any damages to or viruses that may infect
              your computer equipment or other property as the result of your
              access to the Website or your downloading of any content from the
              Website.
            </span>
            <span>
              Notwithstanding the above, if the Company is found liable for any
              proven and actual loss or damage which arises out of or in any way
              connected with any of the occurrences described above, then you
              agree that the liability of Company shall be restricted to, in the
              aggregate, any Service/transactional fees paid by you to the
              Company in connection with such transaction(s)/ Services on this
              Website, if applicable.
            </span>

            <span>
              The Company has no control over the third party websites which
              would be provided to you through its Website. You acknowledge and
              agree that under no circumstance shall the Company be liable for
              your using the services offered or provided by any third party
              service provider.
            </span>
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">Indemnity</h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            <span>
              You agree to indemnify and hold harmless the Company, its
              affiliates, officers, directors, agents, and employees from any
              claims, causes of action, demands, recoveries, losses, damages,
              fines, penalties, or other costs or expenses, including reasonable
              attorneys' fees, arising from or related to your breach of these
              Terms and Conditions, your violation of any law or the rights of a
              third party, or your use of the Website.
            </span>
            <span>
              You also agree not to sue or make any demands or claims against
              the Company, its officers, directors, employees, agents,
              licensees, affiliates, successors, and assigns, and hereby
              irrevocably, unconditionally, and entirely release, waive, and
              forever discharge them (hereinafter "Release") from any and all
              liabilities, claims, demands, losses, suits, costs, and expenses
              (including court costs and reasonable attorney fees), known or
              unknown, in law or equity, which you have had, now have, or may
              have in the future against the Release with respect to the
              Services. Furthermore, you agree to defend, indemnify, and hold
              harmless the Release from any and all Losses resulting from claims
              made against the Company by third parties arising from or in
              connection with this Authorization.
            </span>
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">
            Additional Terms and Conditions
          </h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            <span>
              Company retains the right to modify the Website, related policies,
              and agreements, including the TERMS AND CONDITIONS and Privacy
              Policy at any time it deems necessary. These changes may be made
              to comply with changes in laws or regulations, correct
              inaccuracies, errors, or ambiguities, or to reflect changes in the
              process flow, scope and nature of the Services, company
              reorganization, market practices or customer requirements. Upon
              making any changes, the Company will notify users by posting the
              updated Terms on the Website or through other means. By continuing
              to use the Services and ancillary services, you agree to the
              changes and are bound by the amended Terms. However, if you do not
              agree to the changes, you may discontinue using the Services and
              ancillary services.
            </span>

            <span>
              The Company may temporarily or permanently discontinue or suspend
              the Services and ancillary services by giving reasonable notice,
              except when necessary to change certain features/contents of the
              Services and/or Website or to maintain security and integrity. The
              Company will not be liable for any modification or discontinuance
              of the Services. You are not allowed to use the Services and
              ancillary services for illegal purposes or to transmit material
              that is unlawful, harassing, libellous, invasive of another's
              privacy, abusive, threatening, or obscene, or that infringes the
              rights of others.
            </span>

            <span>
              Company retains the right to modify the Website, related policies,
              and agreements, including the TERMS AND CONDITIONS and Privacy
              Policy at any time it deems necessary. These changes may be made
              to comply with changes in laws or regulations, correct
              inaccuracies, errors, or ambiguities, or to reflect changes in the
              process flow, scope and nature of the Services, company
              reorganization, market practices or customer requirements. Upon
              making any changes, the Company will notify users by posting the
              updated Terms on the Website or through other means. By continuing
              to use the Services and ancillary services, you agree to the
              changes and are bound by the amended Terms. However, if you do not
              agree to the changes, you may discontinue using the Services and
              ancillary services.
            </span>
          </p>
        </div>

        <div className="mt-10 flex flex-col px-10 md:px-8">
          <h3 className="text-lg font-bold text-[#005cde]">Disclaimer</h3>

          <p className="my-2 flex flex-col gap-8 text-base font-medium leading-[1.8rem]">
            The following terms and conditions represent an agreement between
            you and the Company. By accessing and using the Company's services,
            you agree to comply with and be bound by these terms and conditions.
            The Company reserves the right to modify or update these terms and
            conditions at any time without prior notice. It is your
            responsibility to review these terms and conditions periodically to
            stay informed of any changes. The Company does not guarantee
            uninterrupted or error-free access to its services and shall not be
            liable for any damages arising from the use of its services. The
            Company does not endorse any content posted by users and shall not
            be responsible for any user-generated content. By using the
            Company's services, you acknowledge and agree that any reliance on
            the content posted by other users is at your own risk. The Company
            disclaims all warranties, whether express or implied, regarding the
            accuracy, completeness, or suitability of the information provided
            by its services.
          </p>
        </div>
      </div>
    </section>
  );
};

export default TermsConditionPage;
